# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b1e4e769a0f1d46f56a07caa36425813bc766d847016d9b5fd79da38d8ae1e0eef7d57a2ff8fcc8d23c4323fef886198aa0f0b91292ae45fcfcf2114aeef452

test:
  secret_key_base: bffe9819763c9af5a0264d5db06e1e02c5b303d99cb46dd8cf606700c1b4e07fa7db372ae38a60d6fd5f7ad47ecc58d088039ea097c0703324f118c1baedf8fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
